<?php

namespace App\Tests;

use App\Entity\Order;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class OrderTest extends KernelTestCase
{
    /** @var EntityManagerInterface */
    private $entityManager;

    protected function setUp(): void
    {
        $kernel = self::bootKernel();

        DatabasePrimer::prime($kernel);

        $this->entityManager = $kernel->getContainer()->get('doctrine')->getManager();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->entityManager->close();
        $this->entityManager = null;
    }

    /** @test  */
    public function an_order_can_be_created_in_the_database(): void
    {
        $orderCode = time();
        $order = new Order();
        $order->setUserId(1);
        $order->setProductId(3);
        $order->setAddress('test address');
        $order->setQuantity(3);
        $order->setOrderCode($orderCode);

        $this->entityManager->persist($order);

        $this->entityManager->flush();

        $orderRepository = $this->entityManager->getRepository(Order::class);

        $orderRecord = $orderRepository->find(1);

        $this->assertEquals(1, $orderRecord->getUserId());
        $this->assertEquals(3, $orderRecord->getProductId());
        $this->assertEquals('test address', $orderRecord->getAddress());
        $this->assertEquals(3, $orderRecord->getQuantity());
        $this->assertEquals($orderCode, $orderRecord->getOrderCode());
    }
}
